export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_SUCCESSFULL = 'SIGN_IN_SUCCESSFULL';
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';
export const OTP_CONFIRM = 'OTP_CONFIRM';
export const OTP_CONFIRM_SUCCESS = 'OTP_CONFIRM_SUCCESS';
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS';
export const CONFIRM_OTP_SUCCESSfull= 'CONFIRM_OTP_SUCCESSfull';

export const INVALID_EMAIL_AND_PASSWORD = "INVALID_EMAIL_AND_PASSWORD";
export const INVALID_EMAIL_AND_PASSWORD_SUCCESS = "INVALID_EMAIL_AND_PASSWORD_SUCCESS";